using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Dofus.Files.GameData.ItemCriterion
{
    public enum CriterionRealName
    {
        UnusableItem = CriterionEnum.BI,
        BaseAgility = CriterionEnum.Ca,
        TotalAgility = CriterionEnum.CA,
        BaseChance = CriterionEnum.Cc,
        TotalChance = CriterionEnum.CC,
        CurrentEnergy = CriterionEnum.Ce,
        MaxEnergy = CriterionEnum.CE,
        Dishonor = CriterionEnum.CD,
        Honor = CriterionEnum.CH,
        BaseIntelligence = CriterionEnum.Ci,
        TotalIntelligence = CriterionEnum.CI,
        CurrentLife = CriterionEnum.CL,
        MovementPoints = CriterionEnum.CM,
        ActionPoints = CriterionEnum.CP,
        BaseStrength = CriterionEnum.Cs,
        TotalStrength = CriterionEnum.CS,
        BaseVitality = CriterionEnum.Cv,
        TotalVitality = CriterionEnum.CV,
        BaseWisdom = CriterionEnum.Cw,
        TotalWisdom = CriterionEnum.CW,
        TackleEvade = CriterionEnum.Ct,
        TackleBlock = CriterionEnum.CT,
        AlignmentLevel = CriterionEnum.Pa,
        SoulStone = CriterionEnum.PA,
        Friendlist = CriterionEnum.Pb,
        Subarea = CriterionEnum.PB,
        PremiumAccount = CriterionEnum.Pe,
        Emote = CriterionEnum.PE,
        MountRided = CriterionEnum.Pf,
        Gift = CriterionEnum.Pg,
        Breed = CriterionEnum.PG,
        Skill1 = CriterionEnum.Pi,
        Skill2 = CriterionEnum.PI,
        Job1 = CriterionEnum.PJ,
        Job2 = CriterionEnum.Pj,
        Kama = CriterionEnum.PK,
        Level = CriterionEnum.PL,
        Name = CriterionEnum.PN,
        HaveObject = CriterionEnum.PO,
        PVPRank1 = CriterionEnum.Pp,
        PVPRank2 = CriterionEnum.PP,
        Specialization = CriterionEnum.Pr,
        Maried = CriterionEnum.PR,
        Alignment = CriterionEnum.Ps,
        Sex = CriterionEnum.PS,
        Bones = CriterionEnum.PU,
        Weight = CriterionEnum.PW,
        AccountRights = CriterionEnum.PX,
        Subscribe = CriterionEnum.PZ,
        QuestIsActive = CriterionEnum.Qa,
        QuestIsStartable = CriterionEnum.Qc,
        QuestIsDone = CriterionEnum.Qf,
        MapCharacters = CriterionEnum.MK,
        StaticCriterion = CriterionEnum.Sc,
        Month = CriterionEnum.SG,
        Server = CriterionEnum.SI,
        Rank = CriterionEnum.Pq,
        MaxRank = CriterionEnum.PQ,
    }
}
